package com.student.management.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupAllPropertiesEquals(StudentGroup expected, StudentGroup actual) {
        assertStudentGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupAllUpdatablePropertiesEquals(StudentGroup expected, StudentGroup actual) {
        assertStudentGroupUpdatableFieldsEquals(expected, actual);
        assertStudentGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupAutoGeneratedPropertiesEquals(StudentGroup expected, StudentGroup actual) {
        assertThat(expected)
            .as("Verify StudentGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupUpdatableFieldsEquals(StudentGroup expected, StudentGroup actual) {
        assertThat(expected)
            .as("Verify StudentGroup relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupUpdatableRelationshipsEquals(StudentGroup expected, StudentGroup actual) {
        assertThat(expected)
            .as("Verify StudentGroup relationships")
            .satisfies(e -> assertThat(e.getSubjects()).as("check subjects").isEqualTo(actual.getSubjects()));
    }
}
